CUB_ROOT = "./CUB_200_2011"
OUTPUT_DIR = "./dataset_processed"
TARGET_SIZE = (224, 224)
MIN_IMAGES = 500
ALLOW_RELAX_FALLBACK = False

EXTRACT_RECOGNITION_FEATURES = True
CUB_ATTR_CERTAINTY_THRESHOLD = 3
REQUIRE_TORCH_FOR_CNN = True

BUILD_METADATA_DB = True
SQLITE_DB_PATH = "birds.db"
FAISS_INDEX_PATH = "birds.faiss"
FAISS_USE_COSINE = True
